server:
  compression:
    enabled: true
  port: 8080
  tomcat:
    use-relative-redirects: true


#Spring Settings
spring:
  profiles:
    default: local

  mvc:
    path match:
      matching-strategy: ant_path_matcher

   datasource:
    url: jdbc:mysql://localhost:3306/likelion15
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
	naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
spring:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
    web:
      resources:
        static-locations: file:file/,classpath:/static



  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
    encoding: UTF-8

  devtools:
    livereload:
      enabled: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: false

# log level
logging.level:
  org.hibernate.SQL: info
  org.hibernate.type: info
  org.hibernate.type.descriptor.sql: trace
