server:
  compression:
    enabled: true
  port: 8080
  tomcat:
    use-relative-redirects: true


#Spring Settings
spring:
  profiles:
    default: local

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://likelion15.cja02nd5gu0f.ap-northeast-2.rds.amazonaws.com:3306/likelion15
    username: root
    password: qwer0609!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
    encoding: UTF-8

  devtools:
    livereload:
      enabled: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: false

# log level
logging.level:
  org.hibernate.SQL: info
  org.hibernate.type: info
  org.hibernate.type.descriptor.sql: trace
